name: Build iOS Example

on:
  workflow_call:

jobs:
  build-ios-example:
    name: Build iOS Example
    runs-on: macos-latest

    steps:
      - name: Setup Project
        uses: ./.github/actions/setup-node-yarn

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: example/ios

      - name: Install CocoaPods
        working-directory: example/ios
        run: |
          bundle install
          bundle exec pod install

      - name: Build iOS example for simulator
        working-directory: example/ios
        run: |
          xcodebuild \
            -workspace MendixNativeExample.xcworkspace \
            -scheme MendixNativeExample \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build
