name: CI

on:
  pull_request:

jobs:
  lint-and-build:
    name: Lint and Build
    uses: ./.github/workflows/lint-and-build.yml

  build-android:
    name: Build Android
    needs: lint-and-build
    uses: ./.github/workflows/build-android.yml

  build-ios:
    name: Build iOS
    needs: lint-and-build
    uses: ./.github/workflows/build-ios.yml
