name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  android:
    name: Android Build & Test
    needs: lint
    uses: ./.github/workflows/android.yml

  ios:
    name: iOS Build & Test
    needs: lint
    uses: ./.github/workflows/ios.yml
