name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build-android:
    name: Build Android
    needs: lint
    uses: ./.github/workflows/build-android.yml

  build-ios:
    name: Build iOS
    needs: lint
    uses: ./.github/workflows/build-ios.yml
